### ISSUE TITLE
In `transferSpore`, `outPoint` references the spore of another account.

### ISSUE THREAD

**Issue by Dawn-githup** [sporeprotocol/spore-sdk#12]
####Steps to reproduce the behavior:
1.Create a createSore using account A
2.In `transferSpore`, `outPoint` references the spore created by account A.
3.In signAndSendTransaction, use account B.

####example
https://github.com/ShookLyngs/spore-sdk/blob/fef9f042eb85a1293b3c37ff2db347a3049279a7/packages/core/src/__tests__/invisible-fee.test.ts#L94-L120

####Error message
```
Error: {"code":-302,"message":"TransactionFailedToVerify: Verification failed Script(TransactionScriptError { source: Inputs[0].Lock, cause: ValidationFailure: see the error code -31 in the page https://nervosnetwork.github.io/ckb-script-error-codes/by-type-hash/9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8.html#-31 })","data":"Verification(Error { kind: Script, inner: TransactionScriptError { source: Inputs[0].Lock, cause: ValidationFailure: see the error code -31 in the page https://nervosnetwork.github.io/ckb-script-error-codes/by-type-hash/9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8.html#-31 } })"}
```

**Comment by code-monad** [comment]
I think this is an expected behavior cuz you need to provide the proper signature to unlock the cell you  referenced, which account B's signature obviously cannot unlock A's lock

**Comment by Dawn-githup** [comment]
> I think this is an expected behavior cuz you need to provide the proper signature to unlock the cell you referenced, and account B's signature obviously cannot unlock A's lock

The result is expected. Can you determine if it belongs to a lock of a certain address

**Comment by ShookLyngs** [comment]
The cause for the issue is simply because we don't have a protection method that validates the transaction after signing it. 
This issue was hold back because I didn't figured whether we should "resolve" it or not, but recently I've worked on somehting similar in #31 and now I think this is an expected result, as @code-monad mentioned before.

A regular spore transfer looks like this:
```
<>: spore-sdk, []: user-defined
<transferSpore()> -> [signTransaction()] -> [sendTransaction()]
```

As you can see, the signing and sending processes are user-defined actions, which are not controlled by the spore-sdk. If we want to intervene between them, it would be a risky task because we would need to validate the entire transaction. For example, we would need to check the corresponding witness for each input.

So I think at least for now it's expected.

**Comment by ashuralyk** [comment]
@Dawn-githup can this issue be closed?
