### ISSUE TITLE
Change "Predefined" to "Default"

### ISSUE THREAD

**Issue by RongxinZhang** [sporeprotocol/spore-sdk#24]
## Context:
I feel Default is easier to understand than Predefined?
e.g `defaultConfig` or `defaultSetting`

#### Changes:
Inside SDK - [export type PredefinedSporeConfigScriptName = 'Spore' | 'Cluster';](https://github.com/sporeprotocol/spore-sdk/blob/05f2cbe1c03d03e334ebd3b440b5b3b20ec67da7/packages/core/src/config/predefined.ts#L4)

Used in "spore-fire-example" - [const config = predefinedSporeConfigs.Aggron4;](https://github.com/sporeprotocol/spore-first-example/blob/0fd0a79fdbfab06c0d11c08011f457986fa85d93/src/index.ts#L5-L6)

**Comment by ShookLyngs** [comment]
I see two changes in the request:

### 1. Change "predefined" to "default"

The term "predefined" is inherited from [Lumos](https://github.com/ckb-js/lumos/blob/develop/packages/config-manager/src/predefined.ts), it is the foundation of spore-sdk, so I tried to inherit from it as much as possible.

I agree that "default" is a more commonly used word, but I also think "predefined" is acceptable. Instead of changing the names of variables, I feel like for now, we need more documentation covering what users might want to learn. For example, what is SporeConfig and which predefined SopreConfig is suitable for which blockchain/network.

### 2. Remove "spore" from the variable name

When designing, my idea was to keep some uniqueness to the naming of API and variables in the SDK.

Here's an example of a situation I've tried to avoid:

```ts
import { defaultConfigs } from '@spore-sdk/core';
import { defaultConfigs } from 'some-other-package';
```

---

If you're simply trying to improve the readability of [`spore-first-example`](https://github.com/sporeprotocol/spore-first-example/blob/0fd0a79fdbfab06c0d11c08011f457986fa85d93/src/index.ts#L5-L6), maybe we can remove the concept of `SporeConfig` from the `index.ts` file of the example. We can make the `config` parameter optional in `helpers.ts` so then readers/users don't have to learn about it.
